on:
  pull_request_target:
    types: [labeled, unlabeled, opened, synchronize, reopened, ready_for_review]
    paths:
      - "*/ql/src/**/*.ql"
      - "*/ql/src/**/*.qll"
      - "!**/experimental/**"

jobs:
  check-change-note:
    runs-on: ubuntu-latest
    steps:
      - name: Check if change note file is present
        uses: dorny/paths-filter@v2
        id: paths_filter
        with:
          filters: |
            change_note:
              - '**/change-notes/*.md'
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6
      - name: Fail if change note is missing
        uses: actions/github-script@v3
        if: |
          github.event.pull_request.draft == false &&
          steps.paths_filter.outputs.change_note == 'false' &&
          !contains(steps.pr-labels.outputs.labels, ' no-change-note-required ')
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            core.setFailed('No change note found.' +
            ' Either add one, or add the `no-change-note-required` label.')
